name: grizzly_series
description: Pandas-like Series and DataFrame for Dart
version: 0.0.2-dev
homepage: https://github.com/tejainece/grizzly_series
author: Ravi Teja Gudapati <tejainece@gmail.com>
documentation:

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  grizzly_viz_scales:
    path: ../grizzly_viz_scales

dev_dependencies:
  test: ^0.12.0
