name: grizzly_series
description: Numpy and Pandas like NDArray, Series and DataFrame for Dart
version: 0.2.0
homepage: https://github.com/Grizzly-dart/grizzly_series
author: Ravi Teja Gudapati <tejainece@gmail.com>
documentation:

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  grizzly_array: ^0.2.0
  grizzly_primitives: ^0.2.0
  grizzly_scales: ^0.0.4-dev
    #path: ../grizzly_scales
  text_table: ^2.5.3

dev_dependencies:
  test: ^0.12.0