name: grizzly_series
description: Numpy and Pandas like NDArray, Series and DataFrame for Dart
version: 0.0.16-dev
homepage: https://github.com/Grizzly-dart/grizzly_series
author: Ravi Teja Gudapati <tejainece@gmail.com>
documentation:

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  grizzly_scales: ^0.0.3-dev
    #path: ../grizzly_scales

dev_dependencies:
  test: ^0.12.0
