name: grizzly
description: Pandas-like Series and DataFrame for Dart
version: 0.0.1
homepage: https://github.com/tejainece/grizzly
author: Ravi Teja Gudapati <tejainece@gmail.com>
documentation:

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:

dev_dependencies:
  test: ^0.12.0
