name: grizzly_series
description: Numpy and Pandas like NDArray, Series and DataFrame for Dart
version: 0.4.1
homepage: https://github.com/Grizzly-dart/grizzly_series
author: Ravi Teja Gudapati <tejainece@gmail.com>
documentation:

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  grizzly_array: ^0.4.1
  grizzly_primitives: ^0.4.1
  text_table: ^2.5.4

dev_dependencies:
  test: ^0.12.0

dev_dependency_overrides:
  grizzly_primitives:
    path: ../grizzly_primitives
  grizzly_array:
    path: ../grizzly_array