name: grizzly_series
description: Numpy and Pandas like NDArray, Series and DataFrame for Dart
version: 0.5.0-dev
homepage: https://github.com/Grizzly-dart/grizzly_series
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  grizzly_array:
    path: ../grizzly_array
  #grizzly_primitives: ^0.4.2
  text_table: ^2.6.0

dev_dependencies:
  test: ^1.14.3

dev_dependency_overrides:
  grizzly_primitives:
    path: ../grizzly_primitives
  grizzly_array:
    path: ../grizzly_array